aws:
 access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
 secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
 ec2_endpoint: "ec2.ap-southeast-1.amazonaws.com"
ec2:
 staging:
   image_id: "ami-02581950"
   instance_type: "t1.micro"
 production:
   image_id: "ami-02581950"
   instance_type: "t1.micro"
